# Generated by Django 5.0.6 on 2024-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descritption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('borrowed', 'borrowed')], default='available', max_length=50, verbose_name='Status'),
        ),
    ]
