# Generated by Django 5.0.6 on 2024-05-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirmPassword',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='profilePictures'),
        ),
    ]
