# Generated by Django 5.0.6 on 2024-05-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_signup_confirmpassword_signup_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_app.signup')),
                ('wishlist', models.ManyToManyField(to='project_app.book')),
            ],
        ),
    ]
