# Generated by Django 5.0.6 on 2024-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_alter_profile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='wishlist',
            field=models.ManyToManyField(to='project_app.book'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
