# Generated by Django 5.0.6 on 2024-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_signup_wishlist_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Book ID'),
        ),
    ]
