# Generated by Django 5.0.6 on 2024-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0014_alter_signup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='cart',
            field=models.ManyToManyField(related_name='cart_items', to='project_app.book'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_items', to='project_app.book'),
        ),
    ]
