# Generated by Django 5.0.6 on 2024-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_alter_checkout_card_number_alter_checkout_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='card_number',
            field=models.IntegerField(max_length=19),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.IntegerField(max_length=3),
        ),
    ]
