# Generated by Django 5.0.6 on 2024-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0018_alter_checkout_card_number_alter_checkout_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='card_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.SmallIntegerField(),
        ),
    ]
