# Generated by Django 5.0.6 on 2024-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0019_alter_checkout_card_number_alter_checkout_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='project_app.book'),
        ),
    ]
